apps/content/urls.py
from django.conf.urls import url

from content.views import index, detail, category, label

urlpatterns = [
    url(r'^index/',index,name="主页"),
    url(r'^detail/(?P<id>\d+)', detail, name="详情"),
    url(r'^category/(?P<cate_id>\d+)', category, name="分类"),
    url(r'^label/(?P<doc_id>\d+)', label, name="标签"),

]

apps/msg/urls.py
from django.conf.urls import url

from msg.views import comment

urlpatterns = [
    url(r'^comment/',comment, name="评论"),
]

apps/user/urls.py
from django.conf.urls import url

from user.views import login, reg, mine, send_msg

urlpatterns = [
    url(r'^login/',login,name="登录"),
    url(r'^reg/', reg, name="注册"),
    url(r'^mine/', mine, name="个人页面"),
    url(r'^send_msg/', send_msg, name="发送短信"),
]

blog_two/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
#全文搜索框架
    url(r'^search/', include('haystack.urls',namespace="search")),
    url(r'^content/', include("content.urls",namespace="content")),
    url(r'^user/', include("user.urls", namespace="user")),
    url(r'^msg/', include("msg.urls", namespace="msg")),

]

templates/caty.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="renderer" content="webkit">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  	<meta name="apple-mobile-web-app-status-bar-style" content="black"> 
  	<meta name="apple-mobile-web-app-capable" content="yes">
  	<meta name="format-detection" content="telephone=no">
	<title>分类 - Blog</title>
	<link rel="stylesheet" href="{% static "layui/css/layui.css" %}">
	<link rel="stylesheet" href="{% static "css/common.css" %}">
</head>
<body>
	<header class="layui-bg-cyan">
		<nav class="layui-container">
			<div class="layui-row">
			    <div class="layui-col-md2 logo">
			    	<a href="javascript:;"><img src="http://www.muzhuangnet.com/upload/201610/17/201610171329086541.png"></a>
			    </div>
			    <div class="layui-col-md8 layui-hide-xs">
			    	<ul class="layui-nav layui-bg-cyan">
					  	<li class="layui-nav-item">
					    	<a href="{% url "content:主页" %}">首页</a>
					  	</li>
                        {% for cate in category %}
                        	<li class="layui-nav-item layui-this">
					    	<a href="{% url "content:分类" cate.pk%}">{{ cate.cat_title }}<span class="layui-badge-dot"></span></a>
					  	</li>
                        {% endfor %}


					</ul>
			    </div>
			    <div class="layui-col-md2 layui-hide-xs userinfoBox">
			    	<ul class="layui-nav layui-bg-cyan">
					  	<li class="layui-nav-item">
					    	<a href="javascript:;"><i class="layui-icon layui-icon-search search"></i></a>
					  	</li>
					  	<li class="layui-nav-item" lay-unselect="">
						    <p href="javascript:;"><img src="{{ MEDIA_URL }}{{ user.head }}" class="layui-nav-img">{{ request.session.tel }}</p>
						    <dl class="layui-nav-child">
						      	<dd><a href="{% url "user:个人页面" %}">修改信息</a></dd>

						      	<dd><a href="{% url "user:登录" %}">退了</a></dd>
						    </dl>
						</li>
					</ul>
			    </div>
		   	</div>
		</nav>
	</header>

	<div class="layui-container">
		<div class="layui-row layui-col-space20">
			<div class="layui-col-md8">
				<div class="layui-row">
					
					<div class="layui-card">
					  	<div class="layui-card-body">
					  		<span class="layui-breadcrumb">
							  	<a href="javascript:;">首页</a>
							  	<a href="javascript:;">分类</a>
							  	<a><cite>{{ cate_gory.cat_title }}</cite></a>
							</span>
					  	</div>
					</div>

                    {% for con in content %}
                    <div class="layui-col-md12">
						<div class="main list">
							<div class="subject"><p  class="caty">[{{ cate_gory.cat_title }}]</p><a href="{% url "content:详情" con.pk %}">{{ con.con_title }}</a><em>{{ con.add_time }} 发布</em></div>
							<div class="content layui-row">
								<div class="layui-col-md4 list-img">
									<a href="javascript:;"><img src="{% static "images/300.jpg" %}"></a>
								</div>
								<div class="layui-col-md8">
									<div class="list-text">
                                        {{ con.brief }}
                                    </div>
									<div class="list-stat layui-row">

										<div class="layui-col-xs3 layui-col-md3">
											<i class="layui-icon layui-icon-read"></i>
											<em>12次阅读</em>
										</div>

										<div class="layui-col-xs3 layui-col-md3 alink">
											<a href="{% url "content:详情" con.pk %}" class="layui-btn layui-btn-xs">阅读原文</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
                    {% endfor %}






				</div>
	        </div>
	        <div class="layui-col-md4">
				<div class="layui-row">
					<div class="layui-col-md12">
						<div class="layui-card">
						  	<div class="layui-card-header">
								<span class="layui-breadcrumb" lay-separator="|">
									<a href="javascript:;">站点统计</a>
									<a href="javascript:;">联系站长</a>
								</span>
						  	</div>
						  	<div class="layui-card-body" id="stat" style="display: none;">
						  		<table class="layui-table">
								  	<colgroup>
								    	<col width="120">
								    	<col width="230">
								  	</colgroup>
								  	<tbody>
								    	<tr>
								      		<td>运行时间：</td>
								      		<td>856 天</td>
								    	</tr>
								    	<tr>
								      		<td>发表文章：</td>
								      		<td>1024 篇</td>
								    	</tr>
								    	<tr>
								      		<td>注册用户：</td>
								      		<td>3689 人</td>
								    	</tr>
								  	</tbody>
								</table>
						  	</div>
						  	<div class="layui-card-body" id="binfo">
						  		<table class="layui-table">
								  	<colgroup>
								    	<col width="120">
								    	<col width="230">
								  	</colgroup>
								  	<tbody>
								    	<tr>
								      		<td>QQ：</td>
								      		<td>27941662</td>
								    	</tr>
								    	<tr>
								      		<td>Wechat：</td>
								      		<td>SCHOOP</td>
								    	</tr>
								    	<tr>
								      		<td>qqGroup：</td>
								      		<td>88888888</td>
								    	</tr>
								  	</tbody>
								</table>
						  	</div>
						</div>
					</div>
					<div class="layui-col-md12 margin20"></div>
					<div class="layui-col-md12">
						<div class="layui-card">


						</div>
					</div>
					<div class="layui-col-md12 margin20"></div>
					<div class="layui-col-md12">
						<div class="layui-card">
						  	<div class="layui-card-header">
								<span>
									捐助本站
								</span>
						  	</div>
						  	<div class="layui-card-body" style="text-align: center;">
						    	<img src="{% static "images/link.jpg" %}" style="display: inline-block;">
						    	<br/>
						    	<p>无论多少，都是心意!</p>
						  	</div>
						</div>
					</div>
				</div>
	        </div>
		</div>
	</div>

	<!-- 尾部 -->
	<div class="footer"></div>
	<footer class="layui-bg-cyan">
		<div class="layui-container">
			<div class="layui-row">
				<p>本站部分内容来源于网络，若侵犯到您的利益，请联系站长删除！谢谢！Powered By <a href="https://gitee.com/XzcGroup/XzcBlogTemplate" target="_blank" title="XzcBlogTemplate">XzcBlogTemplate</a></p>
			</div>
		</div>
	</footer>
</body>
<script src="{% static "layui/layui.all.js" %}"></script>

<script>
	layui.carousel.render({
	    elem: '#carousel'
	    ,width: '100%' //设置容器宽度
	    ,arrow: 'always' //始终显示箭头
	    //,anim: 'updown' //切换动画方式
  	});
</script>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="renderer" content="webkit">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  	<meta name="apple-mobile-web-app-status-bar-style" content="black"> 
  	<meta name="apple-mobile-web-app-capable" content="yes">
  	<meta name="format-detection" content="telephone=no">
	<title>首页 - Blog</title>
    <style type="text/css">
        .page{            text-align: center;            margin-top: 50px;        }

.page a,.page span{            text-decoration: none;                       padding: 5px 7px;             cursor: pointer;                }
        .page a:hover,.page span:hover{            color: red;  }
    </style>
	<link rel="stylesheet" href="{% static "layui/css/layui.css" %}">
	<link rel="stylesheet" href="{% static "css/common.css" %}">
    <script src="{% static "javascript/js/jquery-1.10.2.min.js" %}"></script>
</head>
<body>
	<header class="layui-bg-cyan">
		<nav class="layui-container">
			<div class="layui-row">
			    <div class="layui-col-md2 logo">
			    	<a href="javascript:;"><img src="http://www.muzhuangnet.com/upload/201610/17/201610171329086541.png"></a>
			    </div>
			    <div class="layui-col-md8 layui-hide-xs">
			    	<ul class="layui-nav layui-bg-cyan">
					  	<li class="layui-nav-item layui-this">
					    	<a href="{% url "content:主页" %}">首页</a>
					  	</li>
                        {% for cate in category %}
                        <li class="layui-nav-item">
					    	<a href="{% url "content:分类" cate.pk %}">{{ cate.cat_title }}<span class="layui-badge-dot"></span></a>
					  	</li>
                        {% endfor %}

					</ul>
			    </div>
			    <div class="layui-col-md2 layui-hide-xs userinfoBox">
			    	<ul class="layui-nav layui-bg-cyan">
					  	<li class="layui-nav-item">
					    	<a href="{% url "search:haystack_search" %}"><i class="layui-icon layui-icon-search search"></i></a>
					  	</li>
					  	<li class="layui-nav-item" lay-unselect="">
						    <p href="javascript:;"><img src="{{ MEDIA_URL }}{{ request.session.head }}" class="layui-nav-img">{{ request.session.tel }}</p>
						    <dl class="layui-nav-child">
						      	<dd><a href="{% url "user:个人页面" %}">修改信息</a></dd>
						      	<dd><a href="javascript:;">积分：{{ user.score }}</a></dd>
						      	<dd><a href="{% url "user:登录" %}">退了</a></dd>
						    </dl>
						</li>
					</ul>
			    </div>
		   	</div>
		</nav>
	</header>

	<div class="layui-container">
		<div class="layui-row layui-col-space20">
			<div class="layui-col-md8">
				<div class="layui-row">
					<div class="layui-col-md12">
						<div class="layui-carousel" id="carousel">
					  		<div carousel-item>
							    <div><img src="{% static "images/14420254463Z-344b0.jpg" %}" alt=""></div>
							    <div><img src="{% static "images/15104654ujc1dpat.jpg" %}" alt=""></div>
					  		</div>
						</div>
					</div>
					<div class="layui-col-md12 margin20"></div>
					<div class="layui-col-md12">
						<div class="main zdbox">
							<div class="subject"><b>[置顶]</b><a href="javascript:;" title="用DTcms做一个独立博客网站（响应式模板）">用layui做一个独立博客网站（响应式模板）</a><em>2018-12-28 11:53:24 发布</em></div>
							<div class="content">我是巫妖汪，风格迥异的四个我，有着不同的个性，不同的人格，甚至不同的职业。
行险解秘专注探险的我，朝阳蓬勃酷爱嘻哈的我，精工巧匠专注纹身的我，文墨生花文艺气息满满的我。
亦是我，亦非我，我是不一样的烟火。</div>
						</div>
					</div>

                    {% for con in content %}
                    <div class="layui-col-md12 margin20"></div>
					<div class="layui-col-md12">
						<div class="main list">
							<div class="subject"><p class="caty">[热门]</p><a href="{% url "content:详情" con.pk %}" title="">{{ con.con_title }}</a><em>{{ con.updata_time }} 发布</em></div><em score="{{ con.score }}">需要积分：{{ con.score }}</em>
							<div class="content layui-row">
								<div class="layui-col-md4 list-img">
									<a href="{% url "content:详情" con.pk %}"><img src="{% static "images/300.jpg" %}"></a>
								</div>
								<div class="layui-col-md8">
									<div class="list-text">{{ con.brief }}</div>
									<div class="list-stat layui-row">




										<div class="layui-col-xs3 layui-col-md3">
											<i class="layui-icon layui-icon-read"></i>
											<em>12次阅读</em>
										</div>

										<div class="layui-col-xs3 layui-col-md3 alink">
                                            {% if con.score == 0 %}
                                                <a href="{% url "content:详情" con.pk %}" class="layui-btn layui-btn-xs">阅读原文</a>
                                                {% else %}
                                                <a href="javascript:;" id="kyo" class="layui-btn layui-btn-sm layui-btn-danger">需要购买</a>
                                            {% endif %}
{#											<a href="{% url "content:详情" con.pk %}" class="layui-btn layui-btn-xs">阅读原文</a>#}
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
                    {% endfor %}





					<div class="layui-col-md12 margin20"></div>
{#					<div class="layui-col-md12" id="pages"></div>#}
				</div>
	        </div>
	        <div class="layui-col-md4">
				<div class="layui-row">
					<div class="layui-col-md12">
						<div class="layui-card">
						  	<div class="layui-card-header">
								<span class="layui-breadcrumb" lay-separator="|">
									<a href="javascript:;">站点统计</a>
									<a href="javascript:;">联系站长</a>
								</span>
						  	</div>
						  	<div class="layui-card-body" id="stat" style="display: none;">
						  		<table class="layui-table">
								  	<colgroup>
								    	<col width="120">
								    	<col width="230">
								  	</colgroup>
								  	<tbody>
								    	<tr>
								      		<td>运行时间：</td>
								      		<td>856 天</td>
								    	</tr>
								    	<tr>
								      		<td>发表文章：</td>
								      		<td>1024 篇</td>
								    	</tr>
								    	<tr>
								      		<td>注册用户：</td>
								      		<td>3689 人</td>
								    	</tr>
								  	</tbody>
								</table>
						  	</div>
						  	<div class="layui-card-body" id="binfo">
						  		<table class="layui-table">
								  	<colgroup>
								    	<col width="120">
								    	<col width="230">
								  	</colgroup>
								  	<tbody>
								    	<tr>
								      		<td>QQ：</td>
								      		<td>511135556</td>
								    	</tr>
								    	<tr>
								      		<td>Wechat：</td>
								      		<td>kyo911dao</td>
								    	</tr>
								    	<tr>
								      		<td>qqGroup：</td>
								      		<td>88888888</td>
								    	</tr>
								  	</tbody>
								</table>
						  	</div>
						</div>
					</div>
					<div class="layui-col-md12 margin20"></div>
					<div class="layui-col-md12">
						<div class="layui-card">
						  	<div class="layui-card-header">
								<span>
									热门标签
								</span>
						  	</div>
						  	<div class="layui-card-body">
								<table class="layui-table" lay-skin="nob">
								  	<tbody>

                                    {% for doc in docket %}
                                    <tr><td><a href="{% url "content:标签" doc.pk %}">{{ doc.doc_title }}</a></td></tr>
                                    {% endfor %}

								  	</tbody>
								</table>
						  	</div>
						</div>
					</div>
					<div class="layui-col-md12 margin20"></div>
					<div class="layui-col-md12">
						<div class="layui-card">
						  	<div class="layui-card-header">
								<span>
									捐助本站
								</span>
						  	</div>
						  	<div class="layui-card-body" style="text-align: center;">
						    	<img src="{% static "images/link.jpg" %}" style="display: inline-block;">
						    	<br/>
						    	<p>无论多少，都是心意!</p>
						  	</div>
						</div>
					</div>
				</div>
	        </div>
		</div>
	</div>

    <div class="page">
    {% if content.has_previous %}
     <span><a href="{% url "content:主页" %}?page={{ content.previous_page_number }}">上一页</a></span>
    {% endif %}

        {% for p in content.paginator.page_range %}
         <a href="{% url "content:主页" %}/?page={{ p }}">{{ p }}</a>
        {% endfor %}

    {% if content.has_next %}
        <span><a href="{% url "content:主页" %}?page={{ content.next_page_number }}">下一页</a></span>
    {% endif %}

    </div>

	<!-- 尾部 -->
	<div class="footer"></div>
	<footer class="layui-bg-cyan">
		<div class="layui-container">
			<div class="layui-row">
				<p>本站部分内容来源于网络，若侵犯到您的利益，请联系站长删除！谢谢！Powered By <a href="https://gitee.com/XzcGroup/XzcBlogTemplate" target="_blank" title="XzcBlogTemplate">XzcBlogTemplate</a></p>
			</div>
		</div>
	</footer>


<script type="application/javascript">
    $(function () {
        $('#kyo').click(function () {

            var data = {


            }

            $.ajax({
                type:"post",
                url:"",
                data:"",
                dataType:"json",
                success:function (data) {
                    console.debug(111)
                }

            })
        })
    })



</script>
</body>
<script src="{% static "layui/layui.all.js" %}"></script>


<script>
	layui.carousel.render({
	    elem: '#carousel'
	    ,width: '100%' //设置容器宽度
	    ,arrow: 'always' //始终显示箭头
	    //,anim: 'updown' //切换动画方式
  	});
  	{#layui.laypage.render({#}
	  {#  elem: 'pages' //注意，这里的 test1 是 ID，不用加 # 号#}
	  {#  ,count: 1 //数据总数，从服务端得到#}
       {# ,limit:2,#}
{#  	{);#}
</script>
</html>

templates/label.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="renderer" content="webkit">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  	<meta name="apple-mobile-web-app-status-bar-style" content="black"> 
  	<meta name="apple-mobile-web-app-capable" content="yes">
  	<meta name="format-detection" content="telephone=no">
	<title>标签列表页 - Blog</title>
	<link rel="stylesheet" href="{% static "layui/css/layui.css" %}">
	<link rel="stylesheet" href="{% static "css/common.css" %}">
</head>
<body>
	<header class="layui-bg-cyan">
		<nav class="layui-container">
			<div class="layui-row">
			    <div class="layui-col-md2 logo">
			    	<a href="javascript:;"><img src="http://www.muzhuangnet.com/upload/201610/17/201610171329086541.png"></a>
			    </div>
			    <div class="layui-col-md8 layui-hide-xs">
			    	<ul class="layui-nav layui-bg-cyan">
					  	<li class="layui-nav-item">
					    	<a href="{% url "content:主页" %}">首页</a>
					  	</li>
                        {% for cate in category %}
                        <li class="layui-nav-item">
					    	<a href="{% url "content:分类" cate.pk %}">{{ cate.cat_title }}<span class="layui-badge-dot"></span></a>
					  	</li>
                        {% endfor %}



					</ul>
			    </div>
			    <div class="layui-col-md2 layui-hide-xs userinfoBox">
			    	<ul class="layui-nav layui-bg-cyan">
					  	<li class="layui-nav-item">
					    	<a href="{% url "search:haystack_search" %}"><i class="layui-icon layui-icon-search search"></i></a>
					  	</li>
					  	<li class="layui-nav-item" lay-unselect="">
						    <p ><img src="{{ MEDIA_URL }}{{ user.head }}" class="layui-nav-img">{{ request.session.tel }}</p>
						    <dl class="layui-nav-child">
						      	<dd><a href="{% url "user:个人页面" %}">修改信息</a></dd>

						      	<dd><a href="{% url "user:登录" %}">退了</a></dd>
						    </dl>
						</li>
					</ul>
			    </div>
		   	</div>
		</nav>
	</header>

	<div class="layui-container">
		<div class="layui-row layui-col-space20">
			<div class="layui-col-md8">
				<div class="layui-row">
					
					<div class="layui-card">
					  	<div class="layui-card-body">
					  		<span class="layui-breadcrumb">
							  	<a href="javascript:;">首页</a>
							  	<a href="javascript:;">标签</a>
							  	<a><cite>{{ title.doc_title }}</cite></a>
							</span>
					  	</div>
					</div>

                    {% for con in content %}
                    	<div class="layui-col-md12">
						<div class="main list">
							<div class="subject"><a href="javascript:;" class="caty">[热门]</a><a href="javascript:;">{{ con.con_title }}</a><em>{{ con.add_time }}发布</em></div>
							<div class="content layui-row">
								<div class="layui-col-md4 list-img">
									<a href="javascript:;"><img src="{% static "images/300.jpg" %}"></a>
								</div>
								<div class="layui-col-md8">
									<div class="list-text">{{ con.brief }}</div>
									<div class="list-stat layui-row">



										<div class="layui-col-xs3 layui-col-md3 alink">
											<a href="{% url "content:详情" con.pk %}" class="layui-btn layui-btn-xs">阅读原文</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
                    {% endfor %}











				</div>
	        </div>
	        <div class="layui-col-md4">
				<div class="layui-row">
					<div class="layui-col-md12">
						<div class="layui-card">
						  	<div class="layui-card-header">
								<span class="layui-breadcrumb" lay-separator="|">
									<a href="javascript:;">站点统计</a>
									<a href="javascript:;">联系站长</a>
								</span>
						  	</div>
						  	<div class="layui-card-body" id="stat" style="display: none;">
						  		<table class="layui-table">
								  	<colgroup>
								    	<col width="120">
								    	<col width="230">
								  	</colgroup>
								  	<tbody>
								    	<tr>
								      		<td>运行时间：</td>
								      		<td>856 天</td>
								    	</tr>
								    	<tr>
								      		<td>发表文章：</td>
								      		<td>1024 篇</td>
								    	</tr>
								    	<tr>
								      		<td>注册用户：</td>
								      		<td>3689 人</td>
								    	</tr>
								  	</tbody>
								</table>
						  	</div>
						  	<div class="layui-card-body" id="binfo">
						  		<table class="layui-table">
								  	<colgroup>
								    	<col width="120">
								    	<col width="230">
								  	</colgroup>
								  	<tbody>
								    	<tr>
								      		<td>QQ：</td>
								      		<td>27941662</td>
								    	</tr>
								    	<tr>
								      		<td>Wechat：</td>
								      		<td>SCHOOP</td>
								    	</tr>
								    	<tr>
								      		<td>qqGroup：</td>
								      		<td>88888888</td>
								    	</tr>
								  	</tbody>
								</table>
						  	</div>
						</div>
					</div>
					<div class="layui-col-md12 margin20"></div>
					<div class="layui-col-md12">
						<div class="layui-card">
						  	<div class="layui-card-header">
								<span>
									热门标签
								</span>
						  	</div>
						  	<div class="layui-card-body">
								<table class="layui-table" lay-skin="nob">
								  	<tbody>
                                    {% for doc in docket %}
                                    <tr><td><a href="{% url "content:标签" doc.pk %}">{{ doc.doc_title }}</a></td></tr>
                                    {% endfor %}



								  	</tbody>
								</table>
						  	</div>
						</div>
					</div>
					<div class="layui-col-md12 margin20"></div>
					<div class="layui-col-md12">
						<div class="layui-card">
						  	<div class="layui-card-header">
								<span>
									捐助本站
								</span>
						  	</div>
						  	<div class="layui-card-body" style="text-align: center;">
						    	<img src="{% static "images/link.jpg" %}" style="display: inline-block;">
						    	<br/>
						    	<p>无论多少，都是心意!</p>
						  	</div>
						</div>
					</div>
				</div>
	        </div>
		</div>
	</div>

	<!-- 尾部 -->
	<div class="footer"></div>
	<footer class="layui-bg-cyan">
		<div class="layui-container">
			<div class="layui-row">
				<p>本站部分内容来源于网络，若侵犯到您的利益，请联系站长删除！谢谢！Powered By <a href="https://gitee.com/XzcGroup/XzcBlogTemplate" target="_blank" title="XzcBlogTemplate">XzcBlogTemplate</a></p>
			</div>
		</div>
	</footer>
</body>
<script src="{% static "layui/layui.all.js" %}"></script>

<script>
	layui.carousel.render({
	    elem: '#carousel'
	    ,width: '100%' //设置容器宽度
	    ,arrow: 'always' //始终显示箭头
	    //,anim: 'updown' //切换动画方式
  	});
</script>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="renderer" content="webkit">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  	<meta name="apple-mobile-web-app-status-bar-style" content="black"> 
  	<meta name="apple-mobile-web-app-capable" content="yes">
  	<meta name="format-detection" content="telephone=no">
	<title>登陆 - Blog</title>
	<link rel="stylesheet" href="{% static "layui/css/layui.css" %}">
	<link rel="stylesheet" href="{% static "css/common.css" %}">
	<link rel="stylesheet" href="{% static "css/login.css" %}">
</head>
<body>
	<div class="layui-container">
		<div class="layui-row">
			<div class="layui-col-md12 layui-hide-xs xs-hide"></div>
			<div class="layui-col-md4 layui-col-md-offset4 login-main">
				<img src="http://www.muzhuangnet.com/upload/201610/17/201610171329086541.png" class="logo">
				<div class="main formbox">
					<form action="" method="post" accept-charset="utf-8" class="layui-form">
                        {% csrf_token %}
						<div class="inputbox">
							<input type="text" name="tel" value="{{ request.POST.tel }}" required  lay-verify="required" placeholder="请输入手机号" autocomplete="off" class="layui-input">
                            {{ errors.tel.0 }}
						</div>
					    
					    <div class="margin20"></div>
						<div class="inputbox">
					    	<input type="text" name="password" required  lay-verify="required" placeholder="请输入密码" autocomplete="off" class="layui-input">
                            {{ errors.password.0 }}
						</div>





					    <div class="inputbox info">
					    	<input type="checkbox" name="checkbox" lay-skin="primary" checked />
					    	我已阅读并同意<a href="javascript:;">用户协议</a>和<a href="javascript:;">隐私条款</a>
					    </div>

					    <div class="layui-row layui-col-space20 bts">
					    	<div class="layui-col-md6">
                                <input type="submit" value="登录" class="layui-btn" lay-submit lay-filter="formDemo" >
{#					    		<button class="layui-btn" lay-submit lay-filter="formDemo">登陆</button>#}
					    	</div>
					    	<div class="layui-col-md6">
					    		<a href="{% url "user:注册" %}" class="layui-btn layui-btn-normal">去注册</a>
					    	</div>
							<div class="layui-col-md12">
								<a href="{% url "content:主页" %}" class="layui-btn layui-btn-danger">返回首页</a>
							</div>
					    </div>
					</form>
				</div>
			</div>
		</div>
	</div>

</body>
<script src="{% static "layui/layui.all.js" %}"></script>
<script>
	
</script>
</html>